name: Build and deploy

on:
  push:
  # target branch name 
    branches: [branchname]

jobs:
  DeployProd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Build
        run: |
          sudo npm ci
          # add project specific build commands

      - name: zip dist folder
        run: |
          # uncomment below if build step is present
          # tar -czvf dist.tar.gz dist
          
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
            HOSTNAME : ${{ secrets.VM_HOST }}
            USER_NAME : ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd ${{ secrets.TARGET_PATH }}
            git pull
            source ~/.nvm/nvm.sh
            npm install --force
          '
          # uncomment below if build step is present
          # scp dist.tar.gz -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}:${{ secrets.TARGET_PATH }}
          
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} `
          cd ${{ secrets.TARGET_PATH }}
          # uncomment below if build step is present
          # tar -xzvf dist.tar.gz
          # rm dist.tar.gz
          export PATH=$PATH:'/home/ubuntu/.nvm/versions/node/$(nvm current)/bin'
          source ~/.bashrc
          pm2 restart 0
          '
